### ISSUE TITLE
SimulatedAnnealingSampler.sample method return type incorrectly documented

### ISSUE THREAD

**Issue by CrashAndSideburns** [dwavesystems/dwave-neal#107]
**Description**
The return type of the `SimulatedAnnealingSampler.sample` method is said to be "a *dimod* `Response` object" in the docs, a class which is nowhere documented in the `neal` or `dimod` docs.

**To Reproduce**
View [here](https://docs.ocean.dwavesys.com/en/stable/docs_neal/reference/generated/neal.sampler.SimulatedAnnealingSampler.sample.html#neal.sampler.SimulatedAnnealingSampler.sample).

**Expected Behaviour**
The documentation should be changed to reflect that actual return type of `SimulatedAnnealingSampler.sample`, namely `SampleSet`.

**Environment:**
N/A

**Comment by arcondello** [comment]
Agree! Thanks for the bug report!

**Comment by randomir** [comment]
Fixed.
