### ISSUE TITLE
Windows 10 Python 3.6: User doesn't have Visual Studio C++

### ISSUE THREAD

**Issue by sploiber** [dwavesystems/dwave-neal#20]
User on Windows 10, Python 3.6, encounters 
[Error code With Python 3.6.6 (07.18.2018).docx](https://github.com/dwavesystems/dwave-neal/files/2206468/Error.code.With.Python.3.6.6.07.18.2018.docx)
error. it seems to be trying to compile.
perhaps the wheels are out of date on this one?

**Comment by arcondello** [comment]
Hi sploiber, we need to build windows wheels. And wheels for 3.7. Thanks for the bug report!
