### ISSUE TITLE
Doesn't build

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/dwave-neal#32]
**Description**
sphinx-build barfing

**To Reproduce**

1. First problem
make html
Exception occurred:
  File "conf.py", line 65, in <module>
    from neal.package_info import __version__
ImportError: No module named neal.package_info

2. I update conf.py to 
import os
import sys
sys.path.insert(0, os.path.abspath('.'))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
.. Now try again
make html
Exception occurred:
  File "/home/jpasvolsky/Work/MyVirtualEnvironments/neal/dwave-neal/neal/sampler.py", line 32, in <module>
    import neal.simulated_annealing as sa
ImportError: No module named simulated_annealing

**Expected behavior**
Should build

**Environment:**
 - OS: Ubuntu 16.0x and Windows
 - Python version: 2.7

**Additional context**
Latest change to make interruptable seems to have updated file locations but not paths to the files

**Comment by arcondello** [comment]
Did you follow the install instructions for building from source?
```
python setup.py build_ext --inplace
```

**Comment by JoelPasvolsky** [comment]
Well of course if one RTFM before building, as you so politely suggest, it works. But what about a foolproof fix for people who like to do things their own particular way?

**Comment by JoelPasvolsky** [comment]
Building in RtD:

```
import os
import sys
# sys.path.insert(0, os.path.abspath('.'))
# sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
```

Building locally (python setup.py build_ext --inplace):

```
import os
import sys
sys.path.insert(0, os.path.abspath('.'))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
```
