### ISSUE TITLE
Adjust `initial_states` to `num_reads`

### ISSUE THREAD

**Issue by randomir** [dwavesystems/dwave-neal#56]
Currently, if a non-null value for `initial_states` is given (to `.sample()`), the number of states provided has to match the number of reads requested.

To simplify a few common use cases, we can extrapolate (or cut) the list of provided initial states to match `num_reads`.

There are a few ways to do that, so it seems reasonable to provide an additional parameter, e.g.  `initial_states_mapper` so users can control it:
- `exact`: states provided must match the number of reads requested, otherwise we fail (current behaviour)
- `tile`: if a shorter list of states is provided, the missing ones will be derived by tiling / repeating the provided ones, as many times as necessary. If a longer list is provided, it will be truncated.
- `random`: if a shorter list if provided, the missing states will be set to random samples, and if  longer is provided it will be truncated.

**Comment by wbernoudy** [comment]
I think these options are great and they cover a wide range of use cases. I think the default should be `exact`, so if both `initial_states` and `num_reads` are provided (and the additional parameter is not) then an error should be raised if `len(initial_states) != num_reads`.

**Comment by randomir** [comment]
I think it makes more sense to require `num_reads`, but have `initial_states_generator` defaulting to `random` -- so to make the most common use case as short and natural as possible:
```
hundred_randomly_seeded_anneals = Neal().sample(bqm, num_reads=100)
```
