### ISSUE TITLE
Make `num_reads` adapt to `initial_states`, if not explicitly given

### ISSUE THREAD

**Issue by randomir** [dwavesystems/dwave-neal#59]
After #53 and #56 are implemented, it would be convenient to have `num_reads` adapt to the size of the `initial_states`, IFF `initial_states` is non-null and `num_reads` is not provided.

That way it's easier to adaptively sample/anneal off some initial sample set of varying size.

**Comment by wbernoudy** [comment]
:+1: I think this is expected behavior. For the new parameter that #56 will introduce, if it is set to `tile` or `random`, we may want to require `num_reads` to be provided.

**Comment by randomir** [comment]
Or, we can just use use a default value for `num_reads` (currently 10) in that case. That's backward compatible, and also seems nicer.

For example with the default, we could have:
```
ten_samples = sampler.sample(bqm)

# identical to
ten_samples = sampler.sample(bqm, initial_states_generator='random')

# and
ten_samples = sampler.sample(bqm, initial_states=empty, initial_states_generator='random')
```
vs
```
ten_samples = sampler.sample(bqm, num_reads=10)
```

**Comment by randomir** [comment]
On second thought, having implicit number of reads (the current behaviour) *does seem* a bit too magical -- especially if that number is some magic constant. 

I can see `num_reads` defaulting to `1`, like we have on [Tabu.sample](https://docs.ocean.dwavesys.com/projects/tabu/en/latest/reference/sampler.html), or requiring explicit number from the user...
