### ISSUE TITLE
Potential dependency conflicts between dwave-neal and numpy

### ISSUE THREAD

**Issue by NeolithEra** [dwavesystems/dwave-neal#79]
Hi, as shown in the following full dependency graph of **_dwave-neal_**, **_dwave-neal_** requires **_numpy >=1.14.0,<2.0.0_**, **_dwave-neal_** requires **_dimod >=0.7.7_** (dimod 0.9.1 will be installed, i.e., the newest version satisfying the version constraint), and directed dependency **_dimod 0.9.1_** transitively introduces **_numpy >=1.16.0,<2.0.0_**.
Obviously, there are multiple version constraints set for numpy in this project. However, according to pip's “_first found wins_” installation strategy, **_numpy 1.18.4_** (i.e., the newest version satisfying constraint >=1.14.0,<2.0.0) is the actually installed version.
Although the first found package version **_numpy 1.18.4_** just satisfies the later dependency constraint （**_numpy >=1.16.0,<2.0.0_**), such installed version is very close to the upper bound of the version constraint of Numpy specified by **_dimod 0.9.1_** .
Once **_dimod_** upgrades，its newest version will be installed, as **_dwave-neal_** does not specify the upper bound of version constraint for **_dimod_**. Therefore, it will easily cause a dependency conflict (build failure), if the upgraded **_dimod_** version introduces a higher version of Numpy, violating its another version constraint **_>=1.14.0,<2.0.0_**.
According to the release history of **_dimod_**, it habitually upgrates **_Numpy_** in its recent releases. For instance, **_dimod 0.7.0_** upgrated Numpy’s constraint from **_>=1.11.3,<2.0.0_** to **_>=1.14.0,<2.0.0_**, **_dimod 0.8.5_**  upgrated Numpy’s constraint from **_>=1.14.0,<2.0.0_** to **_>=1.15.0,<2.0.0_**, and **_dimod 0.9.0.dev6_** upgrated Numpy’s constraint from **_>=1.15.0,<2.0.0_** to **_>=1.16.0,<2.0.0_**. 
As such, it is a warm warning of a potential dependency conflict issue for dwave-neal.

### Dependency tree
```
dwave-neal - 0.5.4
| +- dimod(install version:0.9.1 version range:>=0.7.7)
| | +- numpy(install version:1.18.4 version range:>=1.16.0,<2.0.0)
| | +- six(install version:1.14.0 version range:>=1.10.0,<2.0.0)
| +- numpy(install version:1.18.4 version range:>=1.14.0,<2.0.0)
| +- six(install version:1.14.0 version range:>=1.11.0,<2.0.0) 
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Suggested Solution 
1.	Loosen the version range of **_numpy_** to be **_>=1.14.0_**.
2.	Remove your direct dependency **_numpy_**, and use the **_numpy_** transitively introduced by **_dimod_**.
3.	Change your direct dependency **_dimod_** to be **_>=0.7.7,<=0.9.1_**.
@randomir Which solution do you prefer, 1 ,2 or 3?
Please let me know your choice. May I pull a request to solve this issue?

**Comment by randomir** [comment]
Thank you for bringing this to our attention, @NeolithEra.

Due to existing dependency on numpy (both in Python and C/Cython code), I'm hesitant to remove the upper bound (ad 1), and/or both bounds/defer to dimod (ad 2).

Third solution is too restrictive; patch updates to dimod should be allowed.

I vote for a variation of (3): `dimod>=0.7.7,<0.10.0`.

**Comment by randomir** [comment]
Obsoleted by move to dwave-samplers.
