### ISSUE TITLE
Sporadic test failure in appveyor 3.6 64 bit

### ISSUE THREAD

**Issue by arcondello** [dwavesystems/dwave-neal#86]
Thought it was a misc failure in #84 , but now the same error came up again.

https://ci.appveyor.com/project/dwave-adtt/dwave-neal/builds/36240502
https://ci.appveyor.com/project/dwave-adtt/dwave-neal/builds/36241188

Have not looked into the cause at all.

**Comment by randomir** [comment]
Check [here](https://github.com/dwavesystems/dwave-neal/commit/838f096d3a601c66f1e7c0d282145bf9512fcc2f) and [there](https://github.com/dwavesystems/dwave-hybrid/commit/6ad26ea0d1edeff1d36ed6cd432955dcb36a4f5f).

**Comment by arcondello** [comment]
Got it, I was more curious why it showed up on the same config, though could def be coincidence. We can always lower the threshold again.

**Comment by randomir** [comment]
Or switch to CircleCI. :smile:

**Comment by randomir** [comment]
Fixed with #99 (drop appveyor) and #103 (drop py36).
